### ISSUE TITLE
wrapr::let: "stringsubs" as the subsMethod default

### ISSUE THREAD

**Issue by AndreMikulec** [WinVector/wrapr#1]
IMHO, keep "stringsubs" as the subsMethod default.  People are already using it in this way.  The method is *not bad.*

IMHO, keep all three subsMethod methods.  People exist that need 'let' to work in different(new) ways.

**Comment by JohnMount** [comment]
Thanks for your input!

I already have feedback that "`stringsubs `" is considered unacceptable  by some (for [example](https://twitter.com/hadleywickham/status/872519184743243776)).  My current strategy is:

1. Keep `wrapr::let()` restricted only to symbol to symbol substitution (not general values).
2. Keep all 3 substitution methods  "`langsubs`", "`stringsubs`", "`subsubs`" in `wrapr::let()` (so those that want or don't want one have an option).
3. Have "`langsubs`" be the default procedure for `wrapr::let()` as it is a very good compromise between power and safety.
4. Supply `wrapr::seval()` (new, now available in the development version) for those that want general string based substitution (please see [`wrapr` issue 1](https://github.com/WinVector/wrapr/issues/1) for some details and examples).

I know this isn't exactly your preference, but I think it is a good compromise among some competing goals.

**Comment by AndreMikulec** [comment]
Thanks.
