### ISSUE TITLE
Macros in R, as.call

### ISSUE THREAD

**Issue by jangorecki** [WinVector/wrapr#11]
Macros in R article is a well made analysis. Thank you very much for sharing.
As a feedback I would like to note that AFAIK the `eval(as.call(c(as.name("fun"), ...)))` should be preferred over do.call. Latter one may impose an overhead when constructing arguments for do.call.

**Comment by JohnMount** [comment]
Interesting.  I'll have to educate myself a bit on the distinction before trying to update based on that.  Thank you for the note.

**Comment by JohnMount** [comment]
I've added a link to your note towards the end of the document.  Thanks for contributing the point.

**Comment by jangorecki** [comment]
This can be good intro to the problem
https://grokbase.com/t/r/r-devel/11644r9pbm/rd-call-do-call-expression-too-big
AFAIU you should avoid providing objects, but try to refer to them by variable names.

**Comment by nathaneastwood** [comment]
@jangorecki the link no longer works

**Comment by nathaneastwood** [comment]
I think maybe it's this one: https://r.789695.n4.nabble.com/call-do-call-expression-too-big-td3574335.html

**Comment by JohnMount** [comment]
> I think maybe it's this one: https://r.789695.n4.nabble.com/call-do-call-expression-too-big-td3574335.html

That looks like what I remember being behind the earlier link.  Thank you very much.
