### ISSUE TITLE
wrapr::qc doesnt replace c always

### ISSUE THREAD

**Issue by sanjmeh** [WinVector/wrapr#5]
Certain things work with a c() but fails with qc()

Pls checkout SO question [here](https://stackoverflow.com/questions/50432746/wrapr-seems-not-to-work-with-vectors)

**Comment by JohnMount** [comment]
Than you for reporting that. It was a name collision as qc() evaluates in its own environment.  Now documented and fixed in the 1.4.2 version of wrapr.  Thanks again for taking the time to report that and sorry about the trouble.

**Comment by sanjmeh** [comment]
is 1.4.2 on cran? 
Or shall I load it from source?

**Comment by JohnMount** [comment]
1.4.2 isn't on CRAN yet.  CRAN only allows update so often.  So to get the fix you will have to install from Github.  Assuming you have devtools installed the command to do that is: 

```
     # install.packages("devtools")
    devtools::install_github("WinVector/wrapr")
```

**Comment by sanjmeh** [comment]
Done. Thanks.

~~
Sanjay Mehrotra,
Direct: +918023432432
Mobile: +919901182432
